file = open("student.txt", "w")
file.write("Name: Rahul\n")
file.write("Age: 15\n")
file.write("Grade: 10\n")
file.close()
print("Data written successfully!\n")
file = open("student.txt", "r")
data = file.read()
print("Reading File Content:")
print(data)
file.close()