print ("enter ur full name ")
name=(input())
print ("----------------------------")
print (" name in uppercase")
print (name.upper())
print  ("---------------------------")
print (" name in lowercase")
print (name.lower())
print  ("---------------------------")
print (" name count")
print( len(name) - name.count(' '))
print("-----------------------------")
print("replacing all spaces with -")
print (name.replace(" ", "-"))
print ("Check whether the name starts with a vowel or not.")
print ("i didnt learn that ? ____")