print ("hello my name is charvi what is ur name ")
name= input()
print ("now lets play a game ")
print ("enter the first number ")
a=int (input())
print ("enter the second number ")
b=int(input())
print("the sum is ")
c=a+b
print (c)
text= ("my name is charvi mody ")
print (text )
upercase=(text.upper)
print (upercase)