print ("isnumeric")
string= ("34243546")
print (string.isnumeric())
string1= ("/u00bd")
print (string1.isnumeric())
string2= ("123aayu456")
print (string2.isnumeric())
print("---------------------------")
print("isalpha")
string3=("dev")
print (string3.isalpha())
string4=("Charvi mody")
print (string4.isalpha())
string5=("charvi1")
print(string5.isalpha())
print("---------------------------")
print("endswith")
text=("hello charvi")
result=(text.endswith("word"))
print (result)
result1=(text.endswith("charvi"))
print (result1)
print("----------------------------")
print ("startswith")
text1=("hello charvi mody ")
result2=(text.startswith("a,e,i,o,u"))
print (result)
print ("so this means that the text doesn't stat with an vowel")
print("----------------------------")
print("count")
string6=("how can a clam cram in a clean cream can ?")
print (string6.count("can"))
print("----------------------------")
print("capitalize")
string6=("i sAw Sussie In a ShoEshIne sHop")
print (string6.capitalize())
print("----------------------------")
print("uppercase")
string7=("my name is charvi mody")
print(string7.upper())
print("----------------------------")
print("lowercase")
string8=("My NamE iS ChaRvi MoDy")
print(string8.lower())
print("-----------------------------")
print("replace")
string9=("my name is charvi mody")
print(string9.replace("charvi","vinita"))
print("-----------------------------")
print("length")
string10=("charvi mody")
print (len(string10))
print ("-----------------------------")
print ("string declaration")
string11=("i saw sussie sitting")
print ("the first character of the string is : ")
print (string11[0])
print ("the last character of the sentence is :")
print (string11[19])
print ("this is just an another example of the same thing -")
string12=("sammy the shark !")
print ("the 4th letetr is: ")
print(string12[4])
print ("------------------------------")
print ("slicing")
string13=("sarga")
print (string13[0:3])
print ("this is kinda a part of slicing")
print ("revrce step slicing")
string14=("ABCDEFGHI")
print (string14[6:1:-2])
print ("reterns every 2nd time in reverce order from 1 to 6")
print ("--------")
string15=("abcdefghi")
print (string15[6:1:-3])
print ("reterns every 3rd time in reverce order from 1 to 6")
print ("--------")
string16=("JKLMNOPQR")
print (string16[6:1:-1])
print ("reterns every 1st time in reverce order from 1 to 6")
print ("--------")
string17=("STUVWXYZ")
print (string17[6:1:-4])
print ("reterns every 4th time in reverce order from 1 to 6")
print("btw these all were just an example of the same thing reverce slicing while using the step function")
print ("------------------------------")