thistuple=("apple","banana","chery","papaya","mango")
print (thistuple[2:5])
print ("---------------------")
x=("apple","banana","chery")
y=list(x)
y[1]=("kiwi")
x=tuple(y)
print (x)
print("----------------------")
thistuple1=("apple","banana","chery","papay")
y1=list(thistuple1)
y1.append("orange")
thistuple1=tuple(y)
print("----------------------")
thistuple2=("apple","banana","chery","lavander")
y2=("orange")
thistuple2+=y
print (thistuple2)
print("----------------------")
thistuple3=("apple","banana","chery")
y=list(thistuple3)
y.remove("apple")
thistuple3=tuple(y)
print ("----------------------")